### PR TITLE
Fix: race condition between `WriteStream` close and process exit

### PR DESCRIPTION
**Pull request by andrewjanssen**
The process may exit before the `WriteStream` finishes writing to the target file. For example, I have a small release file for which only the first of two stream chunks is downloaded because the process terminates first, resulting in a corrupted file.

Thank you for this useful package!

### CODE REVIEW

**Comment by andrewjanssen** [comment]
The Travis build is failing on node v12, I wonder if it's due to [these](https://github.com/nodejs/node/commit/f0d2df41f8) [close](https://github.com/nodejs/node/commit/d016b9d708) [changes](https://github.com/nodejs/node/commit/eadc3850fe) in Node 14. Assuming that's the problem— since node 12 is EOL, let me know if you would like me to request the `close` event to support node 12, or not.

**Comment by godber** [comment]
Yeah, we should abandon the old node versions, and I've just noticed this is still on TravisCI ... thanks for the PR, we'll get back to you on this one.

**Review by busma13 — APPROVED** [review]
This looks good. Thanks @andrewjanssen 
We'll need to merge #284 first

**Comment by godber** [comment]
@andrewjanssen we've reworked our CI to run in Github and done some package updates, can you update your branch and bump the version in `package.json` to `0.8.10`?

**Comment by andrewjanssen** [comment]
> can you update your branch and bump the version in `package.json` to `0.8.10`?

Done!

**Review by godber — APPROVED** [review]

**Comment by godber** [comment]
Looks great!  Tests pass, thanks for the contribution @andrewjanssen !

**Comment by godber** [comment]
fixes: https://github.com/terascope/fetch-github-release/issues/283

**Pull request merged**
